# Generated by Django 4.2.20 on 2025-04-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=30)),
                ('StockCode', models.CharField(max_length=6)),
                ('Comments', models.TextField()),
                ('StorageDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
