# Generated by Django 4.2.5 on 2025-02-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author_profile_img",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
