# Generated by Django 4.2.5 on 2025-02-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_author_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author_profile_img",
            field=models.ImageField(blank=True, upload_to="author_profiles/"),
        ),
    ]
